spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://81.70.223.9:3307/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: root
    password: 123
    host: 81.70.223.9
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 81.70.223.9
    database: 1
    port: 6380
    password: 123
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/